global:
  # SMTP配置
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@raft-storage.local'
  smtp_auth_username: 'alertmanager@raft-storage.local'
  smtp_auth_password: 'password'
  smtp_require_tls: true

  # 企业微信配置
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_secret: 'YOUR_WECHAT_SECRET'
  wechat_api_corp_id: 'YOUR_CORP_ID'

  # 钉钉配置
  dingtalk_api_url: 'https://oapi.dingtalk.com/robot/send'

# 模板配置
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# 路由配置
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  
  routes:
    # 严重告警路由 - 立即通知所有渠道
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      group_interval: 5s
      repeat_interval: 15m
      
    # 基础设施告警路由
    - match:
        team: infrastructure
      receiver: 'infrastructure-team'
      group_interval: 5m
      repeat_interval: 2h
      
    # 应用告警路由
    - match:
        team: application
      receiver: 'application-team'
      group_interval: 5m
      repeat_interval: 1h
      
    # 数据库告警路由
    - match:
        team: database
      receiver: 'database-team'
      group_interval: 5m
      repeat_interval: 1h
      
    # 存储告警路由
    - match:
        team: storage
      receiver: 'storage-team'
      group_interval: 5m
      repeat_interval: 1h
      
    # 业务告警路由
    - match:
        team: business
      receiver: 'business-team'
      group_interval: 10m
      repeat_interval: 2h
      
    # 监控系统告警路由
    - match:
        team: monitoring
      receiver: 'monitoring-team'
      group_interval: 10m
      repeat_interval: 4h

# 抑制规则配置
inhibit_rules:
  # 如果实例宕机，抑制该实例的其他告警
  - source_match:
      alertname: ServiceDown
    target_match:
      instance: '.*'
    equal: ['instance']

  # 如果磁盘空间严重不足，抑制一般磁盘空间告警
  - source_match:
      alertname: DiskSpaceCritical
    target_match:
      alertname: DiskSpaceLow
    equal: ['instance', 'mountpoint']

  # 如果Raft集群无Leader，抑制其他Raft告警
  - source_match:
      alertname: RaftNoLeader
    target_match_re:
      alertname: 'Raft.*'
    equal: ['cluster']

  # 如果Redis宕机，抑制Redis相关告警
  - source_match:
      alertname: RedisDown
    target_match_re:
      alertname: 'Redis.*'
    equal: ['instance']

# 接收器配置
receivers:
  # 默认接收器
  - name: 'default-receiver'
    email_configs:
      - to: 'admin@raft-storage.local'
        subject: '[Raft Storage] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # 严重告警接收器 - 多渠道通知
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@raft-storage.local,ops@raft-storage.local'
        subject: '[CRITICAL] Raft Storage 严重告警'
        body: |
          🚨 严重告警通知 🚨
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          实例: {{ .Labels.instance }}
          服务: {{ .Labels.job }}
          {{ end }}
          
          请立即处理！
        headers:
          X-Priority: '1'
    
    webhook_configs:
      - url: 'http://webhook-server:8080/alerts/critical'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alertmanager'
            password: 'webhook-secret'

    # 企业微信通知
    wechat_configs:
      - agent_id: '1000001'
        to_user: '@all'
        message: |
          🚨 Raft Storage 严重告警
          
          {{ range .Alerts }}
          告警: {{ .Annotations.summary }}
          描述: {{ .Annotations.description }}
          时间: {{ .StartsAt.Format "15:04:05" }}
          {{ end }}

  # 基础设施团队接收器
  - name: 'infrastructure-team'
    email_configs:
      - to: 'infra@raft-storage.local'
        subject: '[Infrastructure] {{ .GroupLabels.alertname }}'
        body: |
          基础设施告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          实例: {{ .Labels.instance }}
          {{ end }}

    # Slack通知
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#infrastructure'
        username: 'AlertManager'
        title: 'Infrastructure Alert'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          {{ end }}

  # 应用团队接收器
  - name: 'application-team'
    email_configs:
      - to: 'dev@raft-storage.local'
        subject: '[Application] {{ .GroupLabels.alertname }}'
        body: |
          应用告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          服务: {{ .Labels.job }}
          {{ end }}

    # 钉钉通知
    webhook_configs:
      - url: 'https://oapi.dingtalk.com/robot/send?access_token=YOUR_DINGTALK_TOKEN'
        send_resolved: true
        http_config:
          headers:
            Content-Type: 'application/json'
        body: |
          {
            "msgtype": "markdown",
            "markdown": {
              "title": "应用告警通知",
              "text": "{{ range .Alerts }}**{{ .Annotations.summary }}**\n\n{{ .Annotations.description }}\n\n{{ end }}"
            }
          }

  # 数据库团队接收器
  - name: 'database-team'
    email_configs:
      - to: 'dba@raft-storage.local'
        subject: '[Database] {{ .GroupLabels.alertname }}'
        body: |
          数据库告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          实例: {{ .Labels.instance }}
          {{ end }}

  # 存储团队接收器
  - name: 'storage-team'
    email_configs:
      - to: 'storage@raft-storage.local'
        subject: '[Storage] {{ .GroupLabels.alertname }}'
        body: |
          存储告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          节点: {{ .Labels.node_id }}
          {{ end }}

    webhook_configs:
      - url: 'http://storage-webhook:8080/alerts'
        send_resolved: true

  # 业务团队接收器
  - name: 'business-team'
    email_configs:
      - to: 'business@raft-storage.local'
        subject: '[Business] {{ .GroupLabels.alertname }}'
        body: |
          业务告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }}

  # 监控团队接收器
  - name: 'monitoring-team'
    email_configs:
      - to: 'monitoring@raft-storage.local'
        subject: '[Monitoring] {{ .GroupLabels.alertname }}'
        body: |
          监控系统告警通知
          
          {{ range .Alerts }}
          告警名称: {{ .Annotations.summary }}
          告警描述: {{ .Annotations.description }}
          告警级别: {{ .Labels.severity }}
          告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          {{ end }} 