global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'raft-storage-cluster'
    environment: 'local'

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Spring Boot API服务监控
  - job_name: 'raft-api'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'raft-api'
    params:
      format: ['prometheus']

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis-primary'

  # Raft节点监控
  - job_name: 'raft-nodes'
    static_configs:
      - targets: 
          - 'localhost:8051'
          - 'localhost:8052'
          - 'localhost:8053'
    metrics_path: '/metrics'
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        regex: 'localhost:([0-9]+)'
        target_label: node_id
        replacement: '${1}'

  # 自定义业务指标
  - job_name: 'raft-business-metrics'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/api/v1/monitoring/metrics'
    scrape_interval: 30s
    honor_labels: true

  # Grafana监控
  - job_name: 'grafana'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # JVM指标监控
  - job_name: 'jvm-metrics'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    params:
      format: ['prometheus']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'jvm_.*|process_.*|system_.*'
        action: keep 