apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: raft-storage
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: configmap
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'raft-api'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - raft-storage
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: raft-api-service
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http
        metrics_path: '/api/v1/actuator/prometheus'
        scrape_interval: 10s
      
      - job_name: 'redis'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - raft-storage
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: redis-service
      
      - job_name: 'raft-business-metrics'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - raft-storage
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: raft-api-service
        metrics_path: '/api/v1/monitoring/metrics'
        scrape_interval: 30s
