apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: raft-api-vpa
  namespace: raft-storage
  labels:
    app: raft-storage
    component: api
    version: v1.9.0
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: raft-api-deployment
  updatePolicy:
    updateMode: "Auto"  # 自动更新模式
  resourcePolicy:
    containerPolicies:
    - containerName: api
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: raft-node-vpa
  namespace: raft-storage
  labels:
    app: raft-storage
    component: raft-node
    version: v1.9.0
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: raft-node-1
  updatePolicy:
    updateMode: "Off"  # 仅建议模式，不自动更新（StatefulSet更新较复杂）
  resourcePolicy:
    containerPolicies:
    - containerName: raft-node
      minAllowed:
        cpu: 100m
        memory: 128Mi
      maxAllowed:
        cpu: 1000m
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: redis-vpa
  namespace: raft-storage
  labels:
    app: raft-storage
    component: redis
    version: v1.9.0
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: redis
      minAllowed:
        cpu: 50m
        memory: 64Mi
      maxAllowed:
        cpu: 1000m
        memory: 2Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits 