{{- if .Values.api.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "raft-storage.fullname" . }}-jwt-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "raft-storage.labels" . | nindent 4 }}
    component: api
type: Opaque
data:
  jwt-secret: {{ .Values.api.config.jwt.secret | b64enc }}
{{- end }}
