apiVersion: apps/v1
kind: Deployment
metadata:
  name: raft-api-deployment
  namespace: raft-storage
  labels:
    app.kubernetes.io/name: raft-api
    app.kubernetes.io/component: api-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: raft-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: raft-api
        app.kubernetes.io/component: api-server
    spec:
      containers:
      - name: raft-api
        image: raft-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /app/logs
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/v1/monitoring/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/monitoring/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/v1/monitoring/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      volumes:
      - name: config-volume
        configMap:
          name: raft-api-config
      - name: logs-volume
        persistentVolumeClaim:
          claimName: api-logs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-logs-pvc
  namespace: raft-storage
  labels:
    app.kubernetes.io/name: raft-api
    app.kubernetes.io/component: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
